In [3]:
import numpy as np

In [70]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(f"Array: {arr}")

Array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [69]:
while True:
    n = np.random.randint(1, 10)
    if n % 2 == 0:
        break

one_demension = np.random.randint(1, 9, size=n)
two_demension = one_demension.reshape(2, -1)

print(f"One demension array:\n{one_demension}\nTwo demension array:\n{two_demension}")

One demension array:
[2 1 5 4]
Two demension array:
[[2 1]
 [5 4]]


In [68]:
a = np.random.randint(1, 9, size=(2, 2))
b = np.random.randint(1, 9, size=(2, 2))

vertical_folding = np.vstack((a, b))
print(f"Initial array a:\n{a}\nInitial array b:\n{b}\nThe result of vertical folding:\n{vertical_folding}")

Initial array a:
[[4 7]
 [4 5]]
Initial array b:
[[8 3]
 [8 7]]
The result of vertical folding:
[[4 7]
 [4 5]
 [8 3]
 [8 7]]


In [94]:
a = np.array([1,2,3])

repeat_a = np.repeat(a, 3)
tile_a = np.tile(a, 3)
result = np.concatenate((repeat_a, tile_a))

print(f"Input: {a}\n\
Output: {result}")

Input: [1 2 3]
Output: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_elements = np.intersect1d(a, b)
print(f"Common elements between a and b {common_elements}")

Common elements between a and b [2 4]


In [75]:
np.random.seed(100) 
a = np.random.uniform(1,50, 20)

sorted_indices = a.argsort()[::-1]
top_5_indices = sorted_indices[:5]

print(f"Array:\n{a}\n\
Top 5 indices: {top_5_indices}")

Array:
[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Top 5 indices: [15 10  3  7 18]


In [87]:
a_array = np.array([1,2,3,np.nan,5,6,7,np.nan])

a_cleaned = a_array[~np.isnan(a_array)]

print(f"Cleaned array a_array {a_cleaned}")

Cleaned array a_array [1. 2. 3. 5. 6. 7.]


In [90]:
a = np.array([1,2,3,4,5]) 
b = np.array([4,5,6,7,8])

distance_1 = np.sqrt(sum((pow(b[i] - a[i], 2) for i in range(len(a)))))
distance_2 = np.linalg.norm(a - b)

print(f"The Euclidean distance between arrays a and b: {distance_1}\n\
The Euclidean distance between arrays a and b: {distance_2}")

The Euclidean distance between arrays a and b: 6.708203932499369
The Euclidean distance between arrays a and b: 6.708203932499369


In [104]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

unique_values = np.unique(x)

for num in unique_values:
    indices = np.where(x == num)[0]
    if len(indices) > 4: 
        print(f"Number: {num}\nIndex of the 5th repetition: {indices[5]}")

Number: 1
Index of the 5th repetition: 10


In [118]:
np.random.seed(100) 
a = np.random.randint(0, 5, 10)
unique_values = np.unique(a)

output = np.zeros_like(a, dtype=bool)

for num in unique_values:
    indices = np.where(a == num)[0]
    if len(indices) > 1:
        output[indices[1:]] = True
print(f"Input: {a}\nOutput: {output}")

Input: [0 0 3 0 2 4 2 2 2 2]
Output: [False  True False  True False False  True  True  True  True]
