In [2]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 796.2 kB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 9.0 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [69]:
array = np.arange(1, 11)
print(f"Vector with the first 10 natural numbers: {array}")

Vector with the first 10 natural numbers: [ 1  2  3  4  5  6  7  8  9 10]


In [71]:
array = np.zeros((3,3))
print(f"Zero matrix:\n{array}")

Zero matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [72]:
array = np.random.randint(1, 10, size=(5, 5))
print(f"An array of 5x5 random numbers from 1 to 10:\n{array}")

An array of 5x5 random numbers from 1 to 10:
[[1 4 3 3 7]
 [3 6 5 4 1]
 [1 4 4 2 2]
 [6 7 6 1 1]
 [8 1 3 4 1]]


In [73]:
array = np.random.random((4, 4))
print(f"An array of 4x4 random numbers from 0 to 1:\n{array}")

An array of 4x4 random numbers from 0 to 1:
[[0.33381061 0.4046925  0.3852188  0.93440284]
 [0.43612781 0.02884392 0.76370645 0.4451369 ]
 [0.46337283 0.89940716 0.9508394  0.67476975]
 [0.09002636 0.95941788 0.71301681 0.39288574]]


In [21]:
array_1 = np.random.randint(1, 10, size=5)
array_2 = np.random.randint(1, 10, size=5)

add_array = array_1 + array_2
sub_array = array_1 - array_2
mul_array = array_1 * array_2

print(f"First array: {array_1}\nSecond array: {array_2}\n\
Addition: {add_array}\nSubtraction: {sub_array}\n\
Multiplication: {mul_array}")

First array: [1 3 5 4 7]
Second array: [5 9 1 7 7]
Addition: [ 6 12  6 11 14]
Subtraction: [-4 -6  4 -3  0]
Multiplication: [ 5 27  5 28 49]


In [48]:
vector_1 = np.random.randint(0, 10, size=7)
vector_2 = np.random.randint(0, 10, size=7)

dot_product = np.dot(vector_1, vector_2)

print(f"First vector: {vector_1}\nSecond vector: {vector_2}\nDot product: {dot_product}")

First vector: [3 7 9 6 7 1 6]
Second vector: [7 1 0 3 3 8 6]
Dot product: 111


In [74]:
array_1 = np.random.randint(1, 10, size=(2, 2))
array_2 = np.random.randint(1, 10, size=(2, 3))

mult_array = np.dot(array_1, array_2)

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nMultiplication:\n{mult_array}")

First array:
[[8 2]
 [6 8]]
Second array:
[[4 9 9]
 [3 5 4]]
Multiplication:
[[38 82 80]
 [48 94 86]]


In [75]:
array = np.random.randint(1, 10, size=(3, 3))

array_inv = np.linalg.inv(array)

print(f"Array:\n{array}\nInverse matrix:\n{array_inv}")

Array:
[[7 6 6]
 [7 9 8]
 [1 3 7]]
Inverse matrix:
[[ 0.39393939 -0.24242424 -0.06060606]
 [-0.41414141  0.43434343 -0.14141414]
 [ 0.12121212 -0.15151515  0.21212121]]


In [76]:
array = np.random.random((4, 4))

print(f"Array:\n{array}\nTranspose array:\n{array.T}")

Array:
[[0.35697169 0.0327418  0.24539274 0.56541826]
 [0.48702224 0.47764789 0.20789356 0.63005775]
 [0.93194599 0.53852198 0.8522784  0.39976339]
 [0.89072811 0.63747115 0.19970555 0.59951808]]
Transpose array:
[[0.35697169 0.48702224 0.93194599 0.89072811]
 [0.0327418  0.47764789 0.53852198 0.63747115]
 [0.24539274 0.20789356 0.8522784  0.19970555]
 [0.56541826 0.63005775 0.39976339 0.59951808]]


In [77]:
array = np.random.randint(1, 10, size=(3, 4))
vector = np.random.randint(1, 10, size=4)

mult_array = np.dot(array, vector)

print(f"Array:\n{array}\nVector:\n{vector}\nMultiplication:\n{mult_array}")

Array:
[[1 3 6 1]
 [1 9 2 5]
 [4 9 5 2]]
Vector:
[6 9 9 4]
Multiplication:
[ 91 125 158]


In [78]:
array = np.random.random((2, 3))
vector = np.random.random(3)

mult_array = np.dot(array, vector)

print(f"Array:\n{array}\nVector:\n{vector}\nMultiplication:\n{mult_array}")

Array:
[[0.04866137 0.46635587 0.94837383]
 [0.57198909 0.98689937 0.5289822 ]]
Vector:
[0.97900894 0.68807498 0.54275771]
Multiplication:
[0.88326493 1.52615237]


In [79]:
array_1 = np.random.randint(1, 10, size=(2, 2))
array_2 = np.random.randint(1, 10, size=(2, 2))

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nMultiplication by elements:\n{array_1 * array_2}")

First array:
[[8 7]
 [2 9]]
Second array:
[[9 1]
 [1 1]]
Multiplication by elements:
[[72  7]
 [ 2  9]]


In [80]:
array_1 = np.random.randint(1, 10, size=(2, 2))
array_2 = np.random.randint(1, 10, size=(2, 2))

mult_array = np.dot(array_1, array_2)

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nMultiplication:\n{mult_array}")

First array:
[[8 3]
 [4 2]]
Second array:
[[8 5]
 [7 8]]
Multiplication:
[[85 64]
 [46 36]]


In [81]:
array = np.random.randint(1, 100, size=(5, 5))

print(f"Array:\n{array}\nSum:\n{array.sum()}")

Array:
[[ 2  4 55 72 47]
 [13 40 41 74 40]
 [94 81 61 40 40]
 [45 96 28  3 83]
 [86 91 72  4 63]]
Sum:
1275


In [82]:
array_1 = np.random.randint(1, 10, size=(4, 4))
array_2 = np.random.randint(1, 10, size=(4, 4))

difference = array_1 - array_2

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nDifference:\n{difference}")

First array:
[[4 7 8 5]
 [4 2 9 3]
 [2 3 5 7]
 [6 1 7 9]]
Second array:
[[7 2 1 2]
 [2 4 7 5]
 [4 3 5 5]
 [8 6 4 8]]
Difference:
[[-3  5  7  3]
 [ 2 -2  2 -2]
 [-2  0  0  2]
 [-2 -5  3  1]]


In [84]:
array = np.random.random((3,3))

column_sums = np.sum(array, axis = 1)

print(f"Array:\n{array}\nСolumn where the sum of the elements of each row of the array:{column_sums}") 

Array:
[[0.81957675 0.41192258 0.52848177]
 [0.22177409 0.31520532 0.00866313]
 [0.7836497  0.1352348  0.0653512 ]]
Сolumn where the sum of the elements of each row of the array:[1.7599811  0.54564254 0.9842357 ]


In [85]:
array = np.random.randint(1, 5, size=(3, 4))

squared_array = np.square(array)

print(f"Array:\n{array}\nSquared array:\n{squared_array}")

Array:
[[1 2 3 3]
 [4 1 3 1]
 [3 1 4 1]]
Squared array:
[[ 1  4  9  9]
 [16  1  9  1]
 [ 9  1 16  1]]


In [62]:
vector = np.random.randint(1, 50, size=4)

sqrt_vector = np.sqrt(vector)

print(f"Vector: {vector}\nVector with square roots of numbers: {sqrt_vector}")

Vector: [28 41 36 28]
Vector with square roots of numbers: [5.29150262 6.40312424 6.         5.29150262]
